#!/usr/bin/env node
/**
 * update-aktorер.js
 *
 * Reads PROD_Aktörer_*.xlsx from MasterdataRegister\ and embeds the
 * Aktörsnummer → Namn lookup directly into affarsledberikare.html.
 *
 * Run this script whenever the master data file changes:
 *   node scripts/update-aktorer.js
 */

const path = require('path');
const fs   = require('fs');
const xlsx = require('xlsx');

const ROOT         = path.resolve(__dirname, '..');
const REGISTER_DIR = path.join(ROOT, 'MasterdataRegister');
const HTML_FILE    = path.join(ROOT, 'affarsledberikare.html');

// Find the Aktörer Excel file (picks newest if multiple exist)
const files = fs.readdirSync(REGISTER_DIR)
  .filter(f => /Aktörer.*\.xlsx$/i.test(f) && !f.startsWith('~$'))
  .map(f => ({ name: f, mtime: fs.statSync(path.join(REGISTER_DIR, f)).mtimeMs }))
  .sort((a, b) => b.mtime - a.mtime);

if (files.length === 0) {
  console.error('No Aktörer*.xlsx file found in', REGISTER_DIR);
  process.exit(1);
}

const excelPath = path.join(REGISTER_DIR, files[0].name);
console.log('Reading:', files[0].name);

const wb   = xlsx.readFile(excelPath);
const ws   = wb.Sheets[wb.SheetNames[0]];
const data = xlsx.utils.sheet_to_json(ws, { header: 1, defval: '' });
const hdrs = data[0].map(h => String(h).trim().toLowerCase());
const idI  = hdrs.indexOf('aktörsnummer');
const nmI  = hdrs.indexOf('namn');

if (idI === -1 || nmI === -1) {
  console.error('Could not find columns "Aktörsnummer" and "Namn" in', files[0].name);
  process.exit(1);
}

const entries = [];
for (let i = 1; i < data.length; i++) {
  const id = String(data[i][idI] ?? '').trim();
  const nm = String(data[i][nmI] ?? '').trim();
  if (id) entries.push([id, nm]);
}

console.log(`Found ${entries.length} aktörer`);

// Serialize as a JS Map literal
const mapLiteral = 'new Map(' + JSON.stringify(entries) + ')';
const block = `/* AKTORER_DATA_START – generated by update-aktorer.js – do not edit manually */
  let aktorNamnMap = ${mapLiteral};
  /* AKTORER_DATA_END */`;

let html = fs.readFileSync(HTML_FILE, 'utf8');

const START_MARKER = '/* AKTORER_DATA_START';
const END_MARKER   = 'AKTORER_DATA_END */';

const startIdx = html.indexOf(START_MARKER);
const endIdx   = html.indexOf(END_MARKER);

if (startIdx !== -1 && endIdx !== -1) {
  html = html.slice(0, startIdx) + block + html.slice(endIdx + END_MARKER.length);
} else {
  const placeholder = 'let aktorNamnMap = null;  // Map<aktorsnummer, namn> from Aktörer register';
  if (!html.includes(placeholder)) {
    console.error('Could not find injection point in', HTML_FILE);
    process.exit(1);
  }
  html = html.replace(placeholder, block);
}

fs.writeFileSync(HTML_FILE, html, 'utf8');
console.log('Updated', HTML_FILE);
